export const Types = {
  COUNTRIES_LIST: "COUNTRIES_LIST",
  LOAD_EMERGENCY_CONTACTS: "LOAD_EMERGENCY_CONTACTS",
  GET_COUNTRIES: "GET_COUNTRIES",
  PATIENT_STATUS_LIST: "PATIENT_STATUS_LIST",
  PAYMENT_METHODS: "PAYMENT_METHODS"
};
